### ISSUE TITLE
Facing issue with Vm deployment publisher not present in ARM template.json, refer details in comment

### ISSUE THREAD

**Issue by Tausif01** [microsoft/MCW-Securing-Azure-IoT-solutions#21]
{"code":"MarketplacePurchaseEligibilityFailed","details":[{"code":"BadRequest","message":"Offer with PublisherId: 'microsoft_iot_edge', OfferId: 'iot_edge_vm_ubuntu' cannot be purchased due to validation errors. For more information see details. Correlation Id: '348e9704-da28-418a-8361-262252f150f6' Offer with PublisherId: 'microsoft_iot_edge' and OfferId: 'iot_edge_vm_ubuntu' was removed from the marketplace for new purchase. See similar offers here 'https://azuremarketplace.microsoft.com/en-us/marketplace/apps?page=1%26search=microsoft_iot_edge%20iot_edge_vm_ubuntu'. Correlation Id '188babd2-4cf8-44c0-8310-5af20044d69c'.[{\"Offer with PublisherId: 'microsoft_iot_edge' and OfferId: 'iot_edge_vm_ubuntu' was removed from the marketplace for new purchase. See similar offers here 'https://azuremarketplace.microsoft.com/en-us/marketplace/apps?page=1%26search=microsoft_iot_edge%20iot_edge_vm_ubuntu'. Correlation Id '188babd2-4cf8-44c0-8310-5af20044d69c'.\":\"StoreApi\"}]"}],"message":"Marketplace purchase eligibilty check returned errors. See inner errors for details. "}

**Comment by givenscj** [comment]
Thanks, will be reviewing this week and will move to the new sku.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #22
