### ISSUE TITLE
Alias length

### ISSUE THREAD

**Issue by onderyildirim** [microsoft/MCW-Securing-Azure-IoT-solutions#23]
Following "Before the HOL - Securing Azure IoT solutions.md",  Task 2 item 13 requires to enter an alias

   Modify the alias to be something unique such as "[your initials or first name]".

If alias length is more than 9 characters, template validation fails with 

[{\"code\":\"AccountNameInvalid\",\"target\":\"oilwellsstorageXXXXXXXXXXXXX\",\"message\":\"oilwellsstorageXXXXXXXXXXXXX is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only.\"}]

where Alias is XXXXXXXXXXXXX. It would be good to include a warning in instructions to keep Alias length<9

**Comment by givenscj** [comment]
Added minlength and maxlength to the arm template.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #28
