### ISSUE TITLE
Template file Cosmos DB locations

### ISSUE THREAD

**Issue by onderyildirim** [microsoft/MCW-Securing-Azure-IoT-solutions#24]
Template file MCW-Securing-Azure-IoT-solutions/Hands-on lab/Resources/template.json has static references to Australian datacenters at lines 201 and 207

"locationName": "Australia East",
"locationName": "Australia Southeast",

For this reason cosmosdb creation may fail with not enough resources being available in the region.

Solution coulod be template.json referring to the default region set by resource group

**Comment by givenscj** [comment]
Removed the static locations from the template.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #28
