### ISSUE TITLE
post-install-script01.ps1 fails during template deployment

### ISSUE THREAD

**Issue by JuergenSchwertl** [microsoft/MCW-Securing-Azure-IoT-solutions#25]
post-install-script01.ps1 fails on downloading Git apparently in line 110 trying to write to file 'C:\\Windows\\system32\\config\\systemprofile\\AppData\\Local\\Temp\\git.exe'
causing further steps to fail leaving you without the Ubuntu VM

post-install-script01.ps1 fails during deployment in winExtension with status:
[
    {
        "code": "ComponentStatus/StdOut/succeeded",
        "level": "Info",
        "displayStatus": "Provisioning succeeded",
        "message": "Progress: 98% - Saving 519.08 MB of 525.91 MB\r\nProgress: 98% - Saving 519.22 MB of 525.91 MB\r\nProgress: 98% - Saving 519.38 MB of 525.91 MB\r\nProgress: 98% - Saving 519.51 MB of 525.91 MB\r\nProgress: 98% - Saving 519.64 MB of 525.91 MB\r\nProgress: 98% - Saving 519.76 MB of 525.91 MB\r\nProgress: 98% - Saving 519.89 MB of 525.91 MB\r\nProgress: 98% - Saving 520.01 MB of 525.91 MB\r\nProgress: 98% - Saving 520.14 MB of 525.91 MB\r\nProgress: 98% - Saving 520.26 MB of 525.91 MB\r\nProgress: 98% - Saving 520.39 MB of 525.91 MB\r\nProgress: 98% - Saving 520.51 MB of 525.91 MB\r\nProgress: 98% - Saving 520.64 MB of 525.91 MB\r\nProgress: 99% - Saving 520.76 MB of 525.91 MB\r\nProgress: 99% - Saving 520.87 MB of 525.91 MB\r\nProgress: 99% - Saving 521 MB of 525.91 MB\r\nProgress: 99% - Saving 521.12 MB of 525.91 MB\r\nProgress: 99% - Saving 521.26 MB of 525.91 MB\r\nProgress: 99% - Saving 521.39 MB of 525.91 MB\r\nProgress: 99% - Saving 521.51 MB of 525.91 MB\r\nProgress: 99% - Saving 521.64 MB of 525.91 MB\r\nProgress: 99% - Saving 521.76 MB of 525.91 MB\r\nProgress: 99% - Saving 521.92 MB of 525.91 MB\r\nProgress: 99% - Saving 522.06 MB of 525.91 MB\r\nProgress: 99% - Saving 522.19 MB of 525.91 MB\r\nProgress: 99% - Saving 522.33 MB of 525.91 MB\r\nProgress: 99% - Saving 522.45 MB of 525.91 MB\r\nProgress: 99% - Saving 522.56 MB of 525.91 MB\r\nProgress: 99% - Saving 522.69 MB of 525.91 MB\r\nProgress: 99% - Saving 522.81 MB of 525.91 MB\r\nProgress: 99% - Saving 522.94 MB of 525.91 MB\r\nProgress: 99% - Saving 523.08 MB of 525.91 MB\r\nProgress: 99% - Saving 523.19 MB of 525.91 MB\r\nProgress: 99% - Saving 523.33 MB of 525.91 MB\r\nProgress: 99% - Saving 523.47 MB of 525.91 MB\r\nProgress: 99% - Saving 523.59 MB of 525.91 MB\r\nProgress: 99% - Saving 523.72 MB of 525.91 MB\r\nProgress: 99% - Saving 523.84 MB of 525.91 MB\r\nProgress: 99% - Saving 523.97 MB of 525.91 MB\r\nProgress: 99% - Saving 524.11 MB of 525.91 MB\r\nProgress: 99% - Saving 524.23 MB of 525.91 MB\r\nProgress: 99% - Saving 524.37 MB of 525.91 MB\r\nProgress: 99% - Saving 524.5 MB of 525.91 MB\r\nProgress: 99% - Saving 524.63 MB of 525.91 MB\r\nProgress: 99% - Saving 524.75 MB of 525.91 MB\r\nProgress: 99% - Saving 524.89 MB of 525.91 MB\r\nProgress: 99% - Saving 525.01 MB of 525.91 MB\r\nProgress: 99% - Saving 525.16 MB of 525.91 MB\r\nProgress: 99% - Saving 525.28 MB of 525.91 MB\r\nProgress: 99% - Saving 525.41 MB of 525.91 MB\r\nProgress: 99% - Saving 525.56 MB of 525.91 MB\r\nProgress: 99% - Saving 525.72 MB of 525.91 MB\r\nProgress: 99% - Saving 525.87 MB of 525.91 MB\r\nProgress: 100% - Completed download of C:\\Windows\\TEMP\\chocolatey\\docker-desktop\\3.3.1\\Docker Desktop Installer.exe (525.91 MB).\r\nDownload of Docker Desktop Installer.exe (525.91 MB) completed.\r\nHashes match.\r\nInstalling docker-desktop...\r\ndocker-desktop has been installed.\r\n  docker-desktop may be able to be automatically uninstalled.\r\nEnvironment Vars (like PATH) have changed. Close/reopen your shell to\r\n see the changes (or in powershell/cmd.exe just type `refreshenv`).\r\n The install of docker-desktop was successful.\r\n  Software installed to 'C:\\Program Files\\Docker\\Docker'\r\n\r\nChocolatey installed 3/3 packages. \r\n See the log for details (C:\\ProgramData\\chocolatey\\logs\\chocolatey.log).\r\nSetting Hide file ext\r\nThe operation completed successfully.\r\n\r\nEnable task history\r\nEnable HyperV\r\nWARNING: Restart is suppressed because NoRestart is specified.\r\n\r\nPath   : \r\nOnline : True\r\n\r\nDownloading MCW git repo\r\nDownloading Azure IoT SDK Repo\r\nCreating reboot task\r\nCreating task with jschwert and Susanne1966!\r\n\r\nActions            : {MSFT_TaskExecAction}\r\nAuthor             : \r\nDate               : \r\nDescription        : \r\nDocumentation      : \r\nPrincipal          : MSFT_TaskPrincipal2\r\nSecurityDescriptor : \r\nSettings           : MSFT_TaskSettings3\r\nSource             : \r\nState              : Ready\r\nTaskName           : MCW Setup Script\r\nTaskPath           : \\\r\nTriggers           : {MSFT_TaskBootTrigger}\r\nURI                : \\MCW Setup Script\r\nVersion            : \r\nPSComputerName     : \r\n\r\nTranscript stopped, output file is C:\\WindowsAzure\\Logs\\CloudLabsCustomScriptExtension.txt\r\n0\r\n\r\n\r\n"
    },
    {
        "code": "ComponentStatus/StdErr/succeeded",
        "level": "Info",
        "displayStatus": "Provisioning succeeded",
        "message": "Invoke-WebRequest : Could not find a part of the path \r\n'C:\\Windows\\system32\\config\\systemprofile\\AppData\\Local\\Temp\\git.exe'.\r\nAt C:\\Packages\\Plugins\\Microsoft.Compute.CustomScriptExtension\\1.10.10\\Downloads\\0\\post-install-script01.ps1:110 char:3\r\n+   Invoke-WebRequest -Uri https://github.com/git-for-windows/git/relea ...\r\n+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], DirectoryNotFoundException\r\n    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.InvokeWebRequestComma \r\n   nd\r\n \r\nstart-process : This command cannot be run due to the error: The system cannot find the file specified.\r\nAt C:\\Packages\\Plugins\\Microsoft.Compute.CustomScriptExtension\\1.10.10\\Downloads\\0\\post-install-script01.ps1:115 char:3\r\n+   start-process \"$productPath\\$productExec\" -ArgumentList $argList -w ...\r\n+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException\r\n    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand\r\n \r\ngit : The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the \r\nspelling of the name, or if a path was included, verify that the path is correct and try again.\r\nAt C:\\Packages\\Plugins\\Microsoft.Compute.CustomScriptExtension\\1.10.10\\Downloads\\0\\post-install-script01.ps1:348 char:1\r\n+ git clone https://github.com/Microsoft/MCW-Securing-Azure-IoT-solutio ...\r\n+ ~~~\r\n    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException\r\n    + FullyQualifiedErrorId : CommandNotFoundException\r\n \r\ngit : The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the \r\nspelling of the name, or if a path was included, verify that the path is correct and try again.\r\nAt C:\\Packages\\Plugins\\Microsoft.Compute.CustomScriptExtension\\1.10.10\\Downloads\\0\\post-install-script01.ps1:351 char:1\r\n+ git clone https://github.com/Azure/azure-iot-sdk-c\r\n+ ~~~\r\n    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException\r\n    + FullyQualifiedErrorId : CommandNotFoundException\r\n \r\n"
    }
]

**Comment by givenscj** [comment]
Switched away from the default TMP folder to a statically created one (c:/temp)
