### ISSUE TITLE
Suggest to add "sudo apt-get install ssh"

### ISSUE THREAD

**Issue by JuergenSchwertl** [microsoft/MCW-Securing-Azure-IoT-solutions#27]
The Ubuntu VM comes bare naked not even with SSH server or net-tools installed. As Copy&Paste doesn't work well between WindowsVM and Ubunto GUI therein you likely end up running SSH on Windows against the Ubuntu VM:
In [Task 2: Update and INstall Azure IoT SDK...](https://github.com/microsoft/MCW-Securing-Azure-IoT-solutions/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Securing%20Azure%20IoT%20solutions.md#task-2-update-and-install-azure-iot-sdk-prerequisites) I suggest to add at the very beginning to install ssh and how to get your IP address so that you can **ssh wsuser@172...**  

i.e. add
```bash
sudo apt-get install ssh
ip address
```

**Comment by givenscj** [comment]
Great suggestion, we can add in next pass.

**Comment by givenscj** [comment]
The VMs were moved around and this was added in the latest version to make things easier.
