### ISSUE TITLE
Security issues with oilwells-server and oilwells-edgevm virtual machines

### ISSUE THREAD

**Issue by ms-vincent** [microsoft/MCW-Securing-Azure-IoT-solutions#29]
There appears to be 5 vulnerabilities that expose the 2 virtual machines that get spun up as part of the ARM template. The issues are:

Secure Shell (SSH) Weak Encryption 
Secure Shell (SSH) Password Authentication Enabled
Secure Shell Exposed to the Internet
Remote Desktop Protocol (RDP) Exposed to the Internet
Remote Desktop Protocol (RDP) Weak Encryption 

I have access to some internal resources that document the steps on how to remediate. Please ping me and I'll provide the steps.

**Comment by DawnmarieDesJardins** [comment]
@givenscj 
Hi Chris, please review and advise.

**Comment by givenscj** [comment]
We will review this on the next pass.  Some of these are supposed to be there (like RDP access). SSH is not open via the NSG, but will review anyway.

**Comment by givenscj** [comment]
We have added disclaimer in two places for lab user to close the ports to all but their internet IP.
