### ISSUE TITLE
Before Hands on Lab Template Deployment not working

### ISSUE THREAD

**Issue by manishakumari1992** [microsoft/MCW-Securing-Azure-IoT-solutions#30]
Hi,
I have been trying this lab for the past 2 days. The template deployment is very time consuming and to top it all never actually gets deployed. It's been running in my machine for almost 2 hours and just failed for the 8th time in 2 days. I am attaching some screenshots here for reference. Please help.

![Error1](https://user-images.githubusercontent.com/54332544/118042866-79987e00-b329-11eb-9b70-9b00ed5ad984.png)
![Error2](https://user-images.githubusercontent.com/54332544/118042871-7a311480-b329-11eb-82c0-685b539af756.png)

**Comment by givenscj** [comment]
Reviewing this today (5/18).

**Comment by givenscj** [comment]
Found the issue, both putty and git downloads and executables were modified/moved and the call was "waited".  I have changed to use Chocolaty for both and verified the needed items are deployed.  I'll be pushing a PR later today to resolve it.

**Comment by givenscj** [comment]
Committed fixes and waiting PR merge.
