### ISSUE TITLE
Marketplace Purchase Eligibility

### ISSUE THREAD

**Issue by Karthikkc123** [microsoft/MCW-Securing-Azure-IoT-solutions#32]
"Azure IoT Edge on Ubuntu" doesn't exist in the Marketplace: In the pre-requisites of the lab, we have an Azure IoT Edge VM to be deployed which when deployed through ARM Template is throwing an error saying - 'The image doesn't exist in Marketplace. "iot_edge_vm_ubuntu" was removed from the marketplace for new purchase'

**Comment by saimachi** [comment]
Hi @Karthikkc123,

I deployed the ARM template without any issues. It doesn't look like the ARM template deploys a special Ubuntu image with the IoT Edge runtime already installed. It seems like it deploys a standard Ubuntu VM.

![image](https://user-images.githubusercontent.com/37318129/124520334-06e3d600-dda1-11eb-9364-b0a4e3613dbe.png)

If you are unable to deploy this standard Ubuntu VM, you can install the IoT Edge runtime manually on the Ubuntu instance in the Windows 10 Hyper-V hypervisor machine. I have confirmed that this works. To find instructions on this, consult Exercise 3.

**Comment by timahenning** [comment]
The lab works as expected.
