### ISSUE TITLE
Sept 2021 Update Suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Securing-Azure-IoT-solutions#33]

**Comment by givenscj** [comment]
Add the following:

- Add new feature coverage of Azure Security Center for IoT
- Add Azure Defender for IoT agentless monitoring.
- Add Azure Sentinel IoT queries and hunting
- Add Device to Edge-Device communication (certificates) - See https://github.com/microsoft/MCW-Securing-Azure-IoT-solutions/issues/18
- Explore switching the IoT VM role outside of Windows 10 with TPM enabled

**Comment by givenscj** [comment]
All suggestions were added to the new labs.
