### ISSUE TITLE
Enhancement: Ex 1, Task 2, step 6 - UI is different

### ISSUE THREAD

**Issue by falloutxAY** [microsoft/MCW-Securing-Azure-IoT-solutions#35]
My UI did not provide "settings". Instead, I accessed it via the blade
![image](https://user-images.githubusercontent.com/19646001/133680764-c7ff8025-79c4-4ed0-a672-0d65afd70494.png)

**Comment by givenscj** [comment]
This was updated in the new PR, be sure you are reviewing that PR.
