### ISSUE TITLE
Found multiple issues in the Lab.

### ISSUE THREAD

**Issue by Karthikkc123** [microsoft/MCW-Securing-Azure-IoT-solutions#42]
1. Instructions are not so clear regarding which linuxVM ( i.e, **either oilwells-d01/oilwells-edge-001 or both**) should be used to perform the steps.
2. Shell-service is not installed in oilwells-d01 linuxVM which caused connection refused error while connecting to PowerShell in WindowsVM.
3. Unable to re-start iotedge service because it's masked. To unmask it, I have to use **systemctl unmask iotedge.service** command which is not mentioned in the labguide.
4. In [Exercise-5 Task-1](https://github.com/microsoft/MCW-Securing-Azure-IoT-solutions/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Securing%20Azure%20IoT%20solutions.md), **unable to find Endpoints in Microsoft Defender Portal**. We need **Microsoft Defender for Endpoints** License to perform exercise-5. Even after applying the License I'm unable to perform this particular exercise. Please check on this license requirement and update the Before Hands-on-lab accordingly.
5. In [Exercise-9 Task-2 Step-10](https://github.com/microsoft/MCW-Securing-Azure-IoT-solutions/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Securing%20Azure%20IoT%20solutions.md), while running the given **sudo python....** command, I'm getting **sudo python command not found** error. Installed python using **sudo apt install python** command and then **sudo python....** command got succeed. Please check on this and update.
6. Encountered multiple UI changes and instructions need to be updated.

**Comment by givenscj** [comment]
1. Added extra instructions/clarification on each exercise
2. This is by design, but the instructions to install were too far down the document, moved it up to where it needs to be
3. Checking into this, will add the step if verified.
4. Made the exercise optional and added a note for the defender setup/config/license.
5. Added the python install command

**Comment by givenscj** [comment]
For #3, you installed both the older agent and the newer agent.  Only one is to be selected.  I have added instructions to clarify this.
