### ISSUE TITLE
Issue in Exercise-7 Task-3

### ISSUE THREAD

**Issue by Karthikkc123** [microsoft/MCW-Securing-Azure-IoT-solutions#45]
In [Exercise-7 Task-3 Step-4](https://github.com/microsoft/MCW-Securing-Azure-IoT-solutions/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Securing%20Azure%20IoT%20solutions.md), Getting mdatp command not found error. Tried by mdate command and got output.
![image](https://user-images.githubusercontent.com/83394010/137671815-fc3106ab-dadf-4434-85ef-34657ab01892.png)

**Comment by DawnmarieDesJardins** [comment]
@Karthikkc123 
Hello!  Please advise if the mdatp software was installed.  Can we close this issue?

**Comment by Karthikkc123** [comment]
Thanks @DawnmarieDesJardins, we can close this issue.
